global:
    scrape_interval: 25s
    evaluation_interval: 25s

scrape_configs:
    - job_name: 'image-service'
      static_configs:
          - targets: ['image-service:4000']

    - job_name: 'prometheus'
      static_configs:
          - targets: ['localhost:9090']
